server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: false
  jwt:
    secret: my-very-very-secure-secret-key-at-least-256-bits-long
    expiration:
      access: 15m
      refresh: 7d